### PR TITLE
Localisations / Translations

### PR DESCRIPTION
**Pull request by deanperry**
Some ecommerce sites may have different languages (e.g. en, de, fr, es). This update adds the Globalize gem and the code needed to add localisations.

This may break current shops if the following commands aren't run. I have only tested it on a local shop for a client and it works well.

Once adding the changes, you'll need to migrate the database to add the translation tables and run these in the rails console to create english product categories & products

```ruby
Shoppe::ProductCategory.all.each do |pc|
  l = pc.translations.new
  l.locale = "en"
  l.name = pc.name
  l.permalink = pc.permalink
  l.description = pc.description
  l.save!
end

Shoppe::Product.all.each do |p|
  l = p.translations.new
  l.locale = "en"
  l.name = p.name
  l.permalink = p.permalink
  l.description = p.description
  l.short_description = p.short_description
  l.save!
end
```

### CODE REVIEW

**Comment by deanperry** [comment]
Thinking about it, I could add the above ruby commands in the migrations...

**Comment by deanperry** [comment]
I've added the migrations so that part is now done :+1:

**Comment by andretanguy** [comment]
When can we expect to see this merged?

**Comment by deanperry** [comment]
Done :+1:

**Comment by andretanguy** [comment]
Great, thanks! Have you published v1.0.8 to Rubygems, or shall we reference the git repo (at master) for these additions?

**Comment by deanperry** [comment]
You can reference the GH repo for the moment. I'll push 1.0.8 soon

**Comment by deanperry** [comment]
Apologies for the delay, v1.0.8 has now been released.

**Comment by sennor** [comment]
This is just more work when you are not using multiple locales... I think it should be extracted to a gem called Shoppe-i18n

**Comment by deanperry** [comment]
Yep, I'll look into doing that. The store I'm working on doesn't need it either

**Pull request merged**
