### PR TITLE
Attachments

### PR DESCRIPTION
**Pull request by deanperry**
Linked with PR #132, Issue #129, #144 and possibly #168 

I've added the Attachment model and `has_many`'s on the Product & ProductCategory models. Most of this was copied from my previous #132  which I closed due to the repo changing & the branch being deleted.

This is still a WIP

### CODE REVIEW

**Comment by sammoore** [comment]
What's the status on this? Anyway I could help? I'm integrating Shoppe in my current project and I was going to build out multiple product images anyway. Diggin' Shoppe :heart_eyes:

**Comment by deanperry** [comment]
I've not had chance to work on this as the project I was using it for is on the back burner at the moment. Feel free to fork my fork though and make any changes

**Comment by laCour** [comment]
I've made a working fork where this is implemented, using @deanperry's commits from #132 and #169: https://github.com/laCour/shoppe. This absolutely needs cleaning up first before I make a pull request. I'd like to fix build issues before doing so.

@adamcooke and @deanperry, are there any official contributing guidelines for Shoppe? I'd like to see some implemented so that the library can be cleaned up, as there are several coding styles scattered throughout.

**Comment by deanperry** [comment]
Great, I'll take a look and test it some time over the weekend

**Comment by IAMZEUS** [comment]
What's the status on this? Any chance we can have multiple product images soon?

**Comment by deanperry** [comment]
I'm closing this as #211 has now been merged

**Pull request closed without merging**
