### PR TITLE
Fix cut off button in order payment section

### PR DESCRIPTION
**Pull request by chrztoph**
Before:
screen shot 2015-10-03 at 10 30 41

After:
screen shot 2015-10-03 at 10 37 57

### CODE REVIEW

**Comment by deanperry** [comment]
Hey, what bug has been fixed? All I can see is that the design has been changed

**Comment by chrztoph** [comment]
Called it a bug because the button is cut off, but you are right, only the design has been changed. Sorry for the misleading commit message.

**Comment by deanperry** [comment]
Ah OK I can see it now

**Comment by chrztoph** [comment]
?

**Pull request merged**
