### PR TITLE
Add multiple categories with nesting

### PR DESCRIPTION
**Pull request by metabren**
This was required for a project of mine, and thought it may be beneficial to others as well.  

It introduces two major changes:

1. It allows a product to have multiple categories.
2. It allows the nesting of categories.

A rake db:migrate is required after this change.  Your existing data (product <--> category relationships) will be migrated to this new structure when this happens.

Here's what it looks like

choosing-a-category

categories-list

category-nesting

---

What I did with regard to multiple categories:

* Add Shoppe::ProductCategorization as join between Shoppe::Product and Shoppe::ProductCategory to allow for multiple product categories per product.
* Modify product form to allow creation and modification of products with multiple product categories.
* Update the product importing logic to be compatible with the new associations.
* Update tests.

And the category nesting:

* Add awesome_nested_set to enable category nesting.  I had to patch their gem to get everything working as it should so there's a reference to that in the Gemfile in addition to the .gemspec.
* Change the product categories index page to show nesting.
* Change the product category detail page to allow choosing of the parent category and to show hierarchy. 
* Add combined_permalink to the product category – allowing a category to return a permalink that is prefixed with each ancestor category's permalink as well.  This combined_permalink respects the value of the new permalink_includes_ancestors flag on the category – which is enabled via checkbox on the category page.

There's definitely room for improvement on the UI side.  Specifically within the category detail page – it may be nice to have some sort of drag-n-drop hierarchy manager instead of only being able to select the parent.

### CODE REVIEW

**Comment by deanperry** [comment]
Did you manage to solve those small issues @metabren

**Comment by rubytree** [comment]
@metabren: I've found another issue. User should not be able to remove category if it has any product associated.

**Comment by andretanguy** [comment]
+1 for this to be finalised and merged :)

**Comment by deanperry** [comment]
Ok I've fixed the validation issue. As for the removal of categories when they have products, that is also fixed :+1:

**Comment by andretanguy** [comment]
Thanks!

**Comment by andretanguy** [comment]
Might need to document the changes required to the frontend as changes will be required: http://screens.oceanshq.com/Screen%20Shot%202015-05-04%20at%2021.22.10.png

**Comment by deanperry** [comment]
Good catch @andretanguy

**Comment by andretanguy** [comment]
Where would you typically document this? Would it go as a code snippet on this issue, or on the tryshoppe documentation portal itself?

**Comment by andretanguy** [comment]
Also one other find: when viewing the Products listing in the Shoppe backend, it only shows the product in the first associated category (e.g. "White Soap" is shown only in "Soaps" category even if its subsequently also associated with the "Bath Soap" category)

**Comment by metabren** [comment]
Thanks for sorting this out @deanperry.  Haven't had any spare time for quite a while now.  @andretanguy indeed.  There are a number of options here, some of them involving repeated products which I didn't think was a nice solution.  Removing the category grouping, and just adding the categories on as another column may be the nicest solution.

**Pull request closed without merging**
