### PR TITLE
Deliver mail later / async

### PR DESCRIPTION
**Pull request by lukeheuer**

### CODE REVIEW

**Comment by lukeheuer** [comment]
This would require a min version of Rails 4.2

**Comment by adamcooke** [comment]
As this requires a minimum version of 4.2, this isn't an acceptable change.

**Comment by lukeheuer** [comment]
Alright maybe there should be fallbacks for lower support. Delivering mail synchronously is pretty rough.

**Comment by lukeheuer** [comment]
Also deliver is deprecated and will be removed in Rails 5. Some fix will need to happen if there are plans to support future Rails versions.

**Pull request closed without merging**
