### PR TITLE
Unify code style

### PR DESCRIPTION
**Pull request by Strnadj**
Some codestyle unifications for controllers / mailers / few views, but iam not able to translate some missing localizations... 

Next thing, is there any reason to use blocks instead of methods in before filters? We can met on Gitter to discuss about that.

### CODE REVIEW

**Comment by Strnadj** [comment]
Next thing, is there any reason to use blocks instead of methods in before filters?

**Comment by bigfive** [comment]
:+1: Is this all manual/regex work? or does your IDE do some of it?

**Comment by lukeheuer** [comment]
RuboCop. This project could benefit from adopting the ruby and rails style guides.

**Comment by deanperry** [comment]
Just seen this PR. For some reason I didn't get an email about it and I see Travis CI hasn't tested it for some reason. Yep I'm up for setting up RuboCop. I use it in a couple of client projects and it can be very handy as well as Brakeman

**Comment by Strnadj** [comment]
@bigfive I have few regexes in vim like this one to change old ruby hash syntax to 1.9+... 

`:%s/:\(\w\+\)\(\s*=>\s*\)/\1: /gc`

@lukeheuer Yes, i will send PR with it....

@deanperry thanks, no problem

**Comment by lukeheuer** [comment]
Awesome stuff @Strnadj  - Incase you haven't seen it, there is an auto correct option for RuboCop (you can run directly in vim too IIRC): https://github.com/bbatsov/rubocop/wiki/Automatic-Corrections

It's aware of optimizations in recent versions of Rails so older syntax such as: 
`redirect_to @order, flash: { alert: e.message }`
can automatically be refactored to:
`redirect_to @order, alert: e.message`

**Comment by Strnadj** [comment]
@lukeheuer No, I haven't seen that, but it's kind a cool :-) Try that, but sometimes is the best option to do this on your own, to be sure ...

**Pull request merged**
